### ISSUE TITLE
Non-canonical structure in libigl-core

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/libigl#23]
Building library directly in the root `buildfile` is a bad practice. In particular, this means that when the library is imported (and thus the `buildfile` that defines the library is loaded), the entire project will be loaded, including the `tests/` subproject.

I understand why you did it this way (to be able to symlink `igl/`) but there is a pretty easy way to achieve that without moving everything into the root `buildfile`: just add another subdirectory, for example:

```
libigl-core
├── libigl-core
│   ├── buildfile
│   └── igl -> ../../upstream/igl
└── tests
```

( I am going to stop reviewing here since there will be quite a few changes to fix this.)

**Comment by boris-kolpackov** [comment]
Expanded on this here: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-main-target-root-buildfile

**Comment by lyrahgames** [comment]
> Building library directly in the root `buildfile` is a bad practice. In particular, this means that when the library is imported (and thus the `buildfile` that defines the library is loaded), the entire project will be loaded, including the `tests/` subproject.

Thanks for the explanation. I wasn't aware of this.

> I understand why you did it this way (to be able to symlink `igl/`) but there is a pretty easy way to achieve that without moving everything into the root `buildfile`: just add another subdirectory, for example:
> 
> ```
> libigl-core
> ├── libigl-core
> │   ├── buildfile
> │   └── igl -> ../../upstream/igl
> └── tests
> ```

I have included  your suggestions in commit referenced above.

> ( I am going to stop reviewing here since there will be quite a few changes to fix this.)

Makes sense. I ran CI tests and have already submitted a new package revision. I will close this issue for now. Feel free to reopen/comment.

> Expanded on this here: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml#dont-main-target-root-buildfile

Thank you for this document! Up to now, I tried to keep track of all best practices for packaging third-party libraries in my personal notes. Please, tell me if you need help with the documentation and think that I might be of some help with that.

**Comment by boris-kolpackov** [comment]
> Up to now, I tried to keep track of all best practices for packaging third-party libraries in my personal notes. Please, tell me if you need help with the documentation and think that I might be of some help with that.

I think what will be helpful is for me to first get the packaging guide to a reasonably complete state (hopefully in the next month or so) and then cross-check it with your list to see if I've missed anything.
